version = "0.3.0"

[module.util]
description = "LENGTH, LIT, MAX, MIN macros"

[module.now]
description = "current time in ISO8601 format"
wiki = 'https://en.wikipedia.org/wiki/ISO_8601'

[module.logging]
description = "compiletime eliminated printf-style logging"
depends = [ "now" ]

[module.fail]
description = "abort-based error handling"
man = "abort(3)"
depends = "logging"

[module.xorshift]
description = "implementation of xorshift64 and xorshift128+"
wiki = 'https://en.wikipedia.org/wiki/Xorshift'
depends = "fail"
libs = "m"
test-pkg = "gsl"

[module.crc]
description = "implementation of CRC16-ccitt"
wiki = 'https://en.wikipedia.org/wiki/Computation_of_cyclic_redundancy_checks'

[module.base32]
description = "implementation of the RFC4648 Base32 encoding"
reference = 'https://datatracker.ietf.org/doc/html/rfc4648'
depends = "util"
test-depends = "xorshift"

[module.hex]
description = "hexadecimal binary encoding"
test-depends = "xorshift"

[module.mark]
description = "realtime frequency calcuration"
depends = [ "fail", "logging" ]

[module.stopwatch]
description = "pausable realtime frequency calcuration"
depends = [ "fail", "logging" ]

[module.test]
description = "test utilities"
depends = [ "fail", "now", "util" ]

[module.file]
description = "read file line-by-line or as a whole"
depends = [ "fail", "logging" ]

[module.landlock]
description = "Linux landlock syscall wrappers and helpers"
reference = 'https://www.kernel.org/doc/html/latest/userspace-api/landlock.html'
man = 'landlock(7)'
depends = "fail"

[module.seccomp]
description = "seccomp syscall wrapper"
reference = 'https://www.kernel.org/doc/html/latest/userspace-api/seccomp_filter.html'
man = 'seccomp(2)'

[module.lua]
description = "Lua error checking and stack helpers"
reference = 'https://www.lua.org/manual/5.4/manual.html#4.4'
depends = [ "fail", "util" ]
pkg = { archlinux = "lua", ubuntu2204 = "lua54" }

[module.uv]
description = "uv error-checking"
reference = 'http://docs.libuv.org/en/v1.x/errors.html#c.uv_err_name'
depends = "fail"

[module.rlimit]
description = "apply strict rlimits"
man = 'setrlimit(2)'
depends = [ "fail", "logging", "util" ]

[module.env]
description = "getenv wrappers"
man = 'getenv(3)'
depends = "fail"

[module.no_new_privs]
description = "prctl(PR_SET_NO_NEW_PRIVS) helper"
reference = 'https://www.kernel.org/doc/html/latest/userspace-api/no_new_privs.html'
man = 'prctl(2)#PR_SET_NO_NEW_PRIVS'
depends = "fail"

[module.nonblock]
description = "helper to set/unset O_NONBLOCK flag"
man = 'fcntl(2)#F_SETFL'
depends = "fail"

[module.char]
description = "helpers to interpret ASCII characters"

[module.devnull]
description = "/dev/null as a filedescriptor"
man = 'zero(4)'
depends = "fail"

[module.path]
description = "path mangling"

[module.xdg]
description = "XDG base directories"
reference = 'https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html'
depends = [ "fail", "path", "util", "logging" ]
