version = "0.1.0"

[module.util]
depends = "fail"

[module.logging]
depends = [ "fail", "util" ]

[module.fail]
depends = "logging"

[module.crc]

[module.base32]
depends = "util"

[module.xorshift]
depends = "fail"
libs = [ "m" ]

[module.stopwatch]
depends = [ "fail", "logging" ]

[module.mark]
depends = [ "fail", "logging" ]

[module.test]
depends = [ "util", "fail" ]

[module.file]
depends = [ "fail", "logging" ]

[module.landlock]
depends = "fail"

[module.lua]
depends = "fail"

[module.uv]
depends = "fail"

[module.rlimit]
depends = [ "fail", "logging", "util" ]
