version = "0.2.0"

[module.util]
description = "LENGTH, LIT, MAX, MIN macros"

[module.now]
description = "current time in ISO8601 format"
wiki = 'https://en.wikipedia.org/wiki/ISO_8601'

[module.logging]
depends = [ "now" ]

[module.fail]
description = "abort-based error handling"
man = "abort(3)"
depends = "logging"

[module.xorshift]
description = "implementation of xorshift64 and xorshift128+"
wiki = 'https://en.wikipedia.org/wiki/Xorshift'
depends = "fail"
libs = "m"
test-pkg = "gsl"

[module.crc]
description = "implementation of CRC16-ccitt"
wiki = 'https://en.wikipedia.org/wiki/Computation_of_cyclic_redundancy_checks'

[module.base32]
description = "implementation of the RFC4648 Base32 encoding"
reference = 'https://datatracker.ietf.org/doc/html/rfc4648'
depends = "util"
test-depends = "xorshift"

[module.stopwatch]
depends = [ "fail", "logging" ]

[module.mark]
depends = [ "fail", "logging" ]

[module.test]
depends = [ "fail", "now", "util" ]

[module.file]
depends = [ "fail", "logging" ]

[module.landlock]
description = "Linux landlock syscalls and helpers"
reference = 'https://www.kernel.org/doc/html/latest/userspace-api/landlock.html'
depends = "fail"

[module.lua]
depends = "fail"

[module.uv]
depends = "fail"

[module.rlimit]
description = "apply strict rlimits"
man = 'setrlimit(2)'
depends = [ "fail", "logging", "util" ]

[module.env]
description = "getenv wrappers"
man = 'getenv(3)'
depends = "fail"

[module.no_new_privs]
description = "prctl(PR_SET_NO_NEW_PRIVS) helper"
reference = 'https://www.kernel.org/doc/html/latest/userspace-api/no_new_privs.html'
man = 'prctl(2)#PR_SET_NO_NEW_PRIVS'
depends = "fail"

[module.nonblock]
description = "helper to set/unset O_NONBLOCK flag"
man = 'fcntl(2)#F_SETFL'
depends = "fail"
