version = "0.1.0"

[module.util]
depends = "fail"

[module.logging]
depends = [ "fail", "util" ]

[module.fail]
depends = "logging"

[module.xorshift]
description = "Implementation of xorshift64 and xorshift128+"
link = 'https://en.wikipedia.org/wiki/Xorshift'
depends = "fail"
libs = "m"
test-pkg = "gsl"

[module.crc]
description = "Implementation of CRC16-ccitt"
link = 'https://en.wikipedia.org/wiki/Computation_of_cyclic_redundancy_checks'

[module.base32]
description = "Implementation of the RFC4648 Base32 encoding"
link = 'https://datatracker.ietf.org/doc/html/rfc4648'
depends = "util"
test-depends = "xorshift"

[module.stopwatch]
depends = [ "fail", "logging" ]

[module.mark]
depends = [ "fail", "logging" ]

[module.test]
depends = [ "util", "fail" ]

[module.file]
depends = [ "fail", "logging" ]

[module.landlock]
description = "Linux landlock syscalls and helpers"
link = 'https://www.kernel.org/doc/html/latest/userspace-api/landlock.html'
depends = "fail"

[module.lua]
depends = "fail"

[module.uv]
depends = "fail"

[module.rlimit]
description = "Apply strict rlimit's"
man = 'setrlimit(2)'
depends = [ "fail", "logging", "util" ]
