#!/bin/bash

set -o nounset -o pipefail -o errexit

PYTHON=${PYTHON-python3}
SCRIPT_DIR=$(readlink -f "$0" | xargs dirname)
VENV=${VENV-$SCRIPT_DIR/.venv}

set +o errexit
$PYTHON -c'import toml' &>/dev/null
EC=$?
set -o errexit

if [ "$EC" -eq 0 ]; then
    exit 0
fi

if [ ! -d "$VENV" ]; then
    $PYTHON -m venv "$VENV"
fi

PYTHON=$VENV/bin/python3
PIP=$VENV/bin/pip3

$PIP install -q "tomlkit>=0.11.6"

. "$VENV/bin/activate"
"$@"
