name: Build and test
on:
  push:
  schedule:
    - cron: "0 0 7 * *"

jobs:
  build-and-test:
    strategy:
      matrix:
        os:
        - image: "ubuntu:24.04"
          arch: "ubuntu2404"
        - image: "ubuntu:22.04"
          arch: "ubuntu2204"
        - image: "archlinux:latest"
          arch: "archlinux"
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os.image }}
    env:
      ARCH: ${{ matrix.os.arch }}
    steps:
    - name: Checkout the prepare.sh script
      uses: actions/checkout@v4
      with:
        sparse-checkout: prepare.sh
        sparse-checkout-cone-mode: false

    - name: Prepare and install dependencies
      run: |
          ./prepare.sh -u
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Run tests
      run: make test
