name: Build and test
on: [ push ]

jobs:
  ubuntu:
    runs-on: ubuntu-24.04
    env:
        ARCH: ubuntu2404
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          git gcc make \
          python3 python3-toml \
          liblua5.4-dev \
          libgsl-dev

    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run tests
      run: make test
