name: Build and test
on:
  push:
  schedule:
    - cron: "0 0 7 * *"

jobs:
  ubuntu:
    strategy:
      matrix:
        image: [ "ubuntu:latest", "ubuntu:22.04", "archlinux:latest" ]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout the prepare.sh script
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        sparse-checkout: .github/prepare.sh
        sparse-checkout-cone-mode: false

    - name: Prepare and install dependencies
      run: .github/prepare.sh -u | tee -a "$GITHUB_ENV"

    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run tests
      run: make test
